# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'sooljottagrae' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sooljottagrae
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.8'
  pod 'RNCryptor',  '3.0.1'
end
